version: "3.8"
services:
  backend:
    build:
      context: .  # Make sure the context is the root of the project, where Dockerfile exists
      dockerfile: Dockerfile
    container_name: flowchart_py_backend
    restart: unless-stopped
    ports:
      - "30056:8000"
    networks:
      - flowchart_network

  frontend:
    build:
      context: .  # Assuming your nginx.dockerfile and frontend are in the root directory
      dockerfile: nginx.dockerfile
    container_name: flowchart_py_frontend
    restart: unless-stopped
    ports:
      - "30057:80"
    networks:
      - flowchart_network

networks:
  flowchart_network:
    driver: bridge
