version: "3.8"
services:
  backend:
    build:
      context: .  # This should point to the directory with the Dockerfile
      dockerfile: Dockerfile
    container_name: flowchart_py_backend
    ports:
      - "30056:8000"
    networks:
      - flowchart_network
    environment:
      - NUM_WORKERS=2
    # Remove the restart policy to avoid continuous restarts
    restart: "no"

  frontend:
    build:
      context: .
      dockerfile: nginx.dockerfile
    container_name: flowchart_py_frontend
    ports:
      - "30057:80"
    networks:
      - flowchart_network

networks:
  flowchart_network:
    driver: bridge
