version: "3.8"
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: flowchart_py_backend
    restart: unless-stopped
    ports:
      - "30056:8000"
    networks:
      - flowchart_network

  frontend:
    build:
      context: .
      dockerfile: nginx.dockerfile
    container_name: flowchart_py_frontend
    restart: unless-stopped
    ports:
      - "30057:80"
    networks:
      - flowchart_network

networks:
  flowchart_network:
    driver: bridge
